### ISSUE TITLE
Should we do a kickstarter fundraising?

### ISSUE THREAD

**Issue by Almantask** [csinn/CSInn#34]
I thought it might be an idea to attract more attention to our community in one more way- kickstarter. The money we get would be completely reinvested back into community: hosting fees, giveaways (pluralsight, udemy, licenses..).

I am having my doubts too, because you might not think I am trustworthy to manage the money. I don't want to get into argument and keep doing what we're- helping for free, making developers more professional, providing a stress-free environment to improve.

I really need everyone's input on this. **Please let me know what you think about it.** I will follow democratic voice.

**Comment by Almantask** [comment]
I would appreciate everyone involved in the project voicing their opinion.

**Comment by trinitrotoluene** [comment]
I personally don't think it's entirely appropriate for an open source project (especially a community website) to look for or receive funding except in some very specific scenarios like corporate sponsorship without having at the very least a working base product. Once the project is at a point where we can start to even consider hosting & deployment costs (which should not be prohibitive especially to begin with), maybe this will seem like a less unappealing path to take.

For the time being, my response to this proposal will however be an emphatic *no*.

(And as for giveaways etc. I believe it would be far more preferable to secure products for giveaways through partnerships/advertising on the completed website, rather than financing them with community money)

**Comment by westonpace** [comment]
Soliciting funds is fine but Kickstarter in particular I don't think would work well.  People that invest in a Kickstarted are going to expect results that are defined ahead of time.  While we can probably make something up I don't know that the project really fits the mold.  If people want to donate money I think they'd be more likely to go a Patreon route or something like that.

I'm not against it by any means I just don't think it is likely to be worth the time and effort invested into creating the campaign.

As for trust concerns, I don't have any.  That is between you and the people giving the money.  If people want to give you money for C# Inn I don't really care what you do with it.  I'll reiterate my earlier point that, no matter how democratic you aim for, I do think this project needs a single owner which may as well be you.

**Comment by Almantask** [comment]
We are not going to doing any fundraising as it really no longer implies on free community. We will choose donations after the website is here.
